### ISSUE TITLE
Expected Outcome of this Homework

### ISSUE THREAD

**Issue by jkblc** [ubsuny/CP1-24-HW1#100]
I was looking over grading and wondering if this code needs to run on a quantum computer to be considered done. Is this homework mostly about learning github and a practice run of Python?

**Comment by p-pxmpo** [comment]
I also have the same question, but I do believe that the more important part of this homework is learning and getting used to github and python.

**Comment by iamtomato761** [comment]
I believe the goal is to just learn GitHub and expand your skills in some way. We don't need a final result or anything. This was just about getting used to tasks and coding. That was my interpretation at least.

**Comment by abruns123** [comment]
My interpretation is that the point is to get us used to coding in Github and collaborating such that we may succeed in more complicated projects in the future.

**Comment by jkblc** [comment]
That makes sense, just checking the consensus.
