### ISSUE TITLE
Merging all the physics documentation into one?

### ISSUE THREAD

**Issue by p-pxmpo** [ubsuny/CP1-24-HW1#104]
Is there going to be a process on how to merge all of the physics documentation into one document? or should we just leave them as is?

**Comment by ojha-aditya** [comment]
Have merged the Physics documentation in a single file in PR #91, but haven't deleted the individual documentation files as of now, if @laserlab approves we could go ahead maybe?

**Comment by p-pxmpo** [comment]
Thanks

**Comment by iamtomato761** [comment]
> Have merged the Physics documentation in a single file in PR #91, but haven't deleted the individual documentation files as of now, if @laserlab approves we could go ahead maybe?

I saw that the PR was merged. Deleting the extra files now to clean up some.
