### ISSUE TITLE
Not received the join invite

### ISSUE THREAD

**Issue by ojha-aditya** [ubsuny/CP1-24-HW1#11]
Could anyone confirm where exactly do we receive the invite to join the CP1 team? I haven't received one yet @laserlab

**Comment by laserlab** [comment]
Check again. It should be via email that is on your github account

**Comment by laserlab** [comment]
Please assign milestone and label to this issue and close if resolved

**Comment by ojha-aditya** [comment]
Got it. Thank you @laserlab
