### ISSUE TITLE
Homework Due Date

### ISSUE THREAD

**Issue by jkblc** [ubsuny/CP1-24-HW1#110]
When is this homework due? UBLearns shows Homework 1 availability ending on October 2, but I thought the deadline was today. Will the homework be continued for another week with an additional project?

**Comment by laserlab** [comment]
I guess that is misleading on UBlearns since it shows the availability, which is not the deadline. The deadline is as discussed in the milestone which is today. I changed it in UBlearns to avoid confusion.
