### ISSUE TITLE
Unable to create new labels

### ISSUE THREAD

**Issue by avgagliardo** [ubsuny/CP1-24-HW1#12]
_Splitting this from this from issue #5_ 

It seems like I am unable to create labels using the [labels page](https://github.com/ubsuny/CP1-24-HW1/labels) as well as with the other interfaces. 

I can assign existing labels to issues, but it doesn't look like I can create a new one. I'm pretty sure that I am on the [cp-21 team](https://github.com/orgs/ubsuny/teams/cp1-24).

Am I doing something wrong or maybe there is another permissions group that I might need to be a member of?

**Comment by laserlab** [comment]
You are correct. They must have changed it see here: https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization

So then for this semester the maintainer has to add the labels. So I take you suggestion and add the brainstorming label

**Comment by laserlab** [comment]
So check if you can add the brainstorming label and then close this issue

**Comment by avgagliardo** [comment]
there we go, looks like its all good now!
