### ISSUE TITLE
IDE

### ISSUE THREAD

**Issue by haiderabbas007** [ubsuny/CP1-24-HW1#14]
Do we have the freedom to use an IDE of our choice?

**Comment by laserlab** [comment]
Yes, however I only support github codespaces.

**Comment by laserlab** [comment]
Please add a label and a milestone to this issue.

**Comment by laserlab** [comment]
Is there anything else or can you close that as resolved?

**Comment by dnxjay** [comment]
To make this assignment easier its probably better to stick with the github codespaces

**Comment by haiderabbas007** [comment]
Got it, wanted to get opinions on different types like VS, pycharm etc. Thanks
