### ISSUE TITLE
CP1 Team Invite

### ISSUE THREAD

**Issue by dnxjay** [ubsuny/CP1-24-HW1#17]
How do i go about getting invited into the CP1 team? Also on a second note, who decides on who gets which tasks? Im abit confused on that part of the assignment.

**Comment by laserlab** [comment]
Eventually the maintainer decides about merging the Pull requests. Homework task assignment is done in issues and for now I decide on it.

**Comment by laserlab** [comment]
Please assign a label and a milestone to this issue

**Comment by dnxjay** [comment]
This issue was solved. Closed.
