### ISSUE TITLE
Typo on README.md

### ISSUE THREAD

**Issue by avgagliardo** [ubsuny/CP1-24-HW1#2]
The word issues is spelled incorrectly in the main README.md

**Comment by laserlab** [comment]
Could you clarify where in the the READ.ME file the typo is

**Comment by avgagliardo** [comment]
The typo is here:
https://github.com/ubsuny/CP1-24-HW1/blob/a48a8961bae8c542c286a1f875c19cdb8a0f1ead/README.md?plain=1#L8
