### ISSUE TITLE
Audience question.

### ISSUE THREAD

**Issue by kylemasc917** [ubsuny/CP1-24-HW1#20]
Who is the expected audience of this project. What level of sophistication should the descriptions be in? What base knowledge do they have? Physicists, students, or general public?

**Comment by laserlab** [comment]
Since it is a public project a broad introduction is always helpful, but it no problem to get into more detail later. That’s why e.g. it also good to explain how to get the code running.

**Comment by kylemasc917** [comment]
Thanks. I will keep it broad for my first pull request and can add more detail later after lecture on Friday.
