### ISSUE TITLE
How to start

### ISSUE THREAD

**Issue by dhamalakamal** [ubsuny/CP1-24-HW1#21]
I have hard time, just thinking how do I get started

**Comment by laserlab** [comment]
Why don’t you try to do as a homework task some documentation about the Bell inequality?

**Comment by laserlab** [comment]
Please assign a label and a milestone to this issue

**Comment by Priyanka-43** [comment]
@dhamalakamal Hi Kamal, we can do documentation part about Bell inequality.

**Comment by dhamalakamal** [comment]
Yes.  Let's first work on the documentation part. 
I think, the work should be divided among the group members so that it will be clear to work on different parts.
