### ISSUE TITLE
How do I get started?

### ISSUE THREAD

**Issue by p-pxmpo** [ubsuny/CP1-24-HW1#22]
Im very new to these software development platforms like git and github. I just finished forking the CP1-24-HW1 and creating a clone of the main repository onto my local computer using the gitbash software, now what? how do I get started with the coding portion?

**Comment by laserlab** [comment]
Check issue #24 and PR #23

**Comment by laserlab** [comment]
add a label and a milestone to this issue

**Comment by dnxjay** [comment]
I myself had similar issues in regards to starting due to lack of experience working with some of the software but realized that looking through some of the issues helps with understanding the material better

**Comment by p-pxmpo** [comment]
thank you @dnxjay
