### ISSUE TITLE
.gitignore urgently missing

### ISSUE THREAD

**Issue by laserlab** [ubsuny/CP1-24-HW1#24]
Check here: https://git-scm.com/docs/gitignore and here https://github.com/github/gitignore

This can be a homework task.

needed for PR #23

**Comment by avgagliardo** [comment]
I stubbed one out for my module's needs. It'll be in the next unit-testing PR if anyone would like to extend it.

**Comment by laserlab** [comment]
~~Can you reference the PR here?~~ Already linked in the original issue

**Comment by laserlab** [comment]
While PR #23 added a PR specific .gitignore, I leave this open if someone takes this over to add cases that are useful for the project.

**Comment by HeshamElsaman** [comment]
I guess PR #54 closes this issue.
