### ISSUE TITLE
Difference between pull request and adding a new file

### ISSUE THREAD

**Issue by ojha-aditya** [ubsuny/CP1-24-HW1#32]
Does anyone know how simply adding/uploading files to the code page of a repository different than a pull request?

**Comment by jkblc** [comment]
Uploading files directly affects the repository immediately and doesn’t involve review, while pull requests involve proposing changes and getting approval before merging. If you upload files directly to the repository, you typically do so on a specific branch that you have forked and preferably created a development branch for. You can then open a pull request to the base on ubsuny.

**Comment by ojha-aditya** [comment]
I see. So it can theoretically be done but is not something that's encouraged? But then doesn't GitHub provide a feature that restricts it altogether by itself?

**Comment by jkblc** [comment]
It is definitely something that is done, but you would typically add the file from your development environment (codespaces etc.) and test it before committing the changes, pushing it to your fork, and opening a pull request. Does that make sense?

**Comment by ojha-aditya** [comment]
Understood, thank you very much!
