### ISSUE TITLE
Project Structure Discussion

### ISSUE THREAD

**Issue by jkblc** [ubsuny/CP1-24-HW1#33]
How does a pull request work when multiple people are working on the same feature and there is not a central file for changes to be committed to? Shouldn't there be a master project structure?

**Comment by ojha-aditya** [comment]
For now I guess @laserlab wanted everyone to submit python/markdown or any other files of their own and later on we can formalize a project structure maybe? Not sure.

**Comment by avgagliardo** [comment]
> How does a pull request work when multiple people are working on the same feature and there is not a central file for changes to be committed to? Shouldn't there be a master project structure?

Typically file structure can be broken up into module-specific needs, so in this case I would say it'd probably be a safe bet to create a new subdirectory in your project directory that's named after your module. That is where you can keep all of the relevant files/resources-- and that is where everyone else can expect to find them (super useful!).

The one thing you definitely want to avoid is creating an identically named file in the main directory that someone else has already made, i.e. 2 different files with the same name in the root directory.

Some things belong in the main project directory, and they can always be rearranged that way later on without much trouble (as long as these things are being tracked), so if you aren't sure I would say there's no harm in making a new directory in your branch and working from there. 


edit: [Here is a link to the branch](https://github.com/avgagliardo/CP1-24-HW1/tree/unit-testing) I used in my PR in case you wanted to reuse the pattern.

**Comment by laserlab** [comment]
yes, once files are merged things can get sorted. It’s hard without any content to sort. If there doubles this can be sorted out as well or the second one doesn’t get merged in the first place in the original form

**Comment by jkblc** [comment]
Alright that makes sense, and a lot of files have been added lately
