### ISSUE TITLE
How to reference a specific comment

### ISSUE THREAD

**Issue by ojha-aditya** [ubsuny/CP1-24-HW1#34]
It was briefly covered in today's class but could someone please clarify once again, how to reference a comment into another issue if we are splitting some long comment from a discussion into one and want to reference to that. It is possible to reference a specific issue but what if we intend to reference the particular comment and not the entire issue thread?

**Comment by SchrodingersStruggle** [comment]
On a comment, you should be able to click on the 3 dots at the top right corner and then hit "reference in new issue". Hope this helps.

**Comment by ojha-aditya** [comment]
Got it, works now! Thanks.
