### ISSUE TITLE
Proposal for Architecture Label

### ISSUE THREAD

**Issue by avgagliardo** [ubsuny/CP1-24-HW1#35]
It might be beneficial to have a **Architecture** label specifically for issues like:

- Where should X file live?
- Where should X outputs be stored?
- How do X and Y parts interface?

There a ton of similar questions that tend to pop up when writing software as a group. We may also want to consider a **Standardization** tag as well to keep certain things like data storage and I/O handling consistent, but maybe for this project it won't be necessary.

**Comment by laserlab** [comment]
You got it

**Comment by avgagliardo** [comment]
Great, thanks!
