### ISSUE TITLE
Project Distribution for Qiskit Code

### ISSUE THREAD

**Issue by SchrodingersStruggle** [ubsuny/CP1-24-HW1#36]
Here we can organize the distribution of tasks regarding working on the qiskit code for the assignment

**Comment by zbpetersbuf** [comment]
O I see ill delete mine then

**Comment by SchrodingersStruggle** [comment]
@zbpetersbuf 
So regarding the projects, I see you're confused about what to do next. I think it's not a big deal if you want to edit your files pulled into main if they aren't complete, you'll just have to open up another pull request which will get you more hw credit.

**Comment by zbpetersbuf** [comment]
So on Friday I planed on finishing the copying the code with a line describing what each line does and then making a code space file with all the code on it to make sure it functions properly

**Comment by zbpetersbuf** [comment]
Well sure but I don't want to step on any toes and do too much, what where you trying to do exactly so I don't do it or make you do too much

**Comment by SchrodingersStruggle** [comment]
Yeah okay, I don't know if you posted any updates last night, but I know last I checked, the section assigning observables was missing, that may be a good addition to get sorted. I can draft up some short descriptions of some of the code in the meantime, does that sound good?

**Comment by zbpetersbuf** [comment]
Alright that sounds good I do what I think I was suppose to but with no comments and not the codespace file yet

**Comment by zbpetersbuf** [comment]
Ok completed the copying, I'll set an alarm for 2 hours if no one tells me not to ill make the codespace file to make sure everything is functioning properly, and make another pull request

**Comment by SchrodingersStruggle** [comment]
Alright sounds good, and when you say you'll make a codespace file to make sure everything functions properly, do you mean opening a codespace and testing the code on that?

**Comment by zbpetersbuf** [comment]
Probably Im new to all this terminology, ill open the codespace, make a file, test the code and then push it into the main branch because I think that's what's needed?

**Comment by SchrodingersStruggle** [comment]
Ah gotcha. I mean I'm new to working on Github too, however I believe you can open a codespace on your forked repository to test the code whenever you want. I've been doing that a good bit myself personally, just to see what works and what doesn't.

**Comment by zbpetersbuf** [comment]
so actually hold on, so someone else gets gets a pull request I won't make a file in codespace since I got my 2 pull requests. So someone who needs to have a pull request all you go to do is copy the code we got down then test and pull request it and your good, so I will not be doing this myself

**Comment by SchrodingersStruggle** [comment]
Yeah sure, I may work on it in a bit, however for now I am trying to get the qiskit.txt and devcontainer files to actually work on vscode because I'm having issues. I won't be able to test that out until I get that sorted which hopefully won't take long

**Comment by laserlab** [comment]
@SchrodingersStruggle Do you mean the codespace is not working or do you try to set up your own VSCode environment?

**Comment by SchrodingersStruggle** [comment]
> @SchrodingersStruggle Do you mean the codespace is not working or do you try to set up your own VSCode environment?

I can get my own codespace working just fine with pip installs in the terminal, I was just trying to get it such that it worked immediately after setting up the codespace.

**Comment by SchrodingersStruggle** [comment]
@zbpetersbuf
I've (hopefully) resolved the problem I was working on with setting up codespaces and created my own pull request for it, so I will now be available to write some descriptions. IBM gives descriptions already to an extent, but I was thinking of describing exactly how some of the steps relate to Bell's inequality (like the entanglement in the classical step). What are your thoughts?

**Comment by laserlab** [comment]
Awesome discussion here! That how it should go!

**Comment by laserlab** [comment]
> Well sure but I don't want to step on any toes and do too much, what where you trying to do exactly so I don't do it or make you do too much

Don’t worry about having multiple solutions. This is always better than having no solution.

**Comment by HeshamElsaman** [comment]
Can I ask to help work on the code part of the assignment as well?

P.S.
I haven't got my invitation to the team yet.

**Comment by SchrodingersStruggle** [comment]
@HeshamElsaman 

Yeah sure of course, if you want a fairy easy contribution you can go to the same location zbpetersbuf mentioned in his code and start working on the second step in optimizing the code for the quantum computers! I know it's not in our main, I haven't looked at the other pull requests or issues to see if someone else claimed it though

**Comment by HeshamElsaman** [comment]
Ok, great! I was just checking the tutorial on the CHSH inequality.
I'll proceed once I finish the part on step 2.
I can't get what you mean by it's not in our main though.
My repo is supposed to be up to date with the main one and I can see the files in mine, however, my issue is that I don't know why my codespace is not showing them. Is that an issue that I should raise?

**Comment by SchrodingersStruggle** [comment]
@HeshamElsaman
You can open an issue for credit if you'd like, but I guess what I mean is that nothing has been pulled into the main branch of the ubsuny repo, so it's likely still an open topic to claim.

**Comment by HeshamElsaman** [comment]
What about that quantumcode.py file then?

**Comment by SchrodingersStruggle** [comment]
Ah my apologies, I just looked at the updated file and the code from step 2 has already been covered. 

Maybe open up a new issue regarding any other open tasks for people to claim along the lines. I am going to be working on adding in line descriptions of the code found in step 1, but maybe the in line descriptions are available for the part 2 code of optimizations.

**Comment by HeshamElsaman** [comment]
Ok, will do so.

**Comment by HeshamElsaman** [comment]
There are still steps 3 and 4 for the code I guess, right?

**Comment by SchrodingersStruggle** [comment]
I am going to close this issue, as I believe this task is sorted with others claiming it.
