### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Priyanka-43** [ubsuny/CP1-24-HW1#39]
What points should we highlight when we are writing about Bell's inequality?

**Comment by avgagliardo** [comment]
> What points should we highlight when we are writing about Bell's inequality?

I would maybe start with a small blurb about its history and who/where it came from, a statement of what it means in plain terms, and why it is important to physics and quantum computing-- or better, how it affects our expectations as we implement the CHSH Inequality on a quantum computer.

**Comment by Priyanka-43** [comment]
Yeah Sure, We can add about Local realism as well.

**Comment by ojha-aditya** [comment]
There was a basic description written by @kylemasc917 in a markdown file, it is still in the pull requests I believe. Maybe we can build on that? 

Maybe it would be a good idea to split the Physics based documentation into different aspects of Bell's inequality?

**Comment by Priyanka-43** [comment]
Yeah I agree with you, I have also create a pull request try to write history part.

**Comment by kylemasc917** [comment]
I finished a brief rundown of the EPR paradox and quantum background and ended by mentioning the paper went unchallenged until bell so you could pick up from there.

**Comment by Priyanka-43** [comment]
I have also completed documentation part and created a pull request.
