### ISSUE TITLE
Referencing a line of code in a comment

### ISSUE THREAD

**Issue by ojha-aditya** [ubsuny/CP1-24-HW1#41]
Could anyone discuss again how to reference a line of code from our own codespace to any comment or an issue? 

I guess a trivial way would be to copy-paste it mentioning python but isn't there a more direct way to do so?

**Comment by p-pxmpo** [comment]
I figured it our just now, go to the code and the line you are trying to reference, click on the line number and 3 dots should appear on the left side, click that then click COPY PERMALINK then paste it on your conmnent / issue.

**Comment by ojha-aditya** [comment]
Is it also the same for codespaces? I am using the codespace Jupyter notebook and do not see this somehow!

**Comment by laserlab** [comment]
You can check https://github.com/ubsuny/CP1-24-HW1/issues/4#issue-2529191344 how it is done there.
If you’re looking for a GUI solution you might check if https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github provides something like it

**Comment by ojha-aditya** [comment]
Thank you @laserlab I will look into it. Closing the issue for now. 

Additionally, is the issue about Python 3.12.6 not working for qiskit closed? I can not seem to find, that is actually where I wanted to reference the error while importing ice cream in 3.9.2.

**Comment by laserlab** [comment]
See #45

**Comment by ojha-aditya** [comment]
Got it. I guess there is no need to reference the error message anymore if there is a temporary workaround as discussed in #45.
