### ISSUE TITLE
Ideas about documenting the Physics of Bell's inequality 

### ISSUE THREAD

**Issue by ojha-aditya** [ubsuny/CP1-24-HW1#42]
Splitting from #39, would it be a good idea to divide the documentation of the Physics of Bell's inequality, into different aspects of the same? 

For example:

1. History of Bell's Inequality and Hidden Variables
2. Mathematics
3. Implications for Quantum Computation and Information Processing
4. Experimental tests for Bell's Inequality

That way we could mostly avoid repetition as well as start thinking about the structuring as was mentioned in #33

**Comment by Priyanka-43** [comment]
Yes, this sounds good. I am currently working on History of Bell's Inequality.

**Comment by laserlab** [comment]
Please add content through PRs so it can be be merged. Content can alsways be changed after a PR. A PR does not have to include the final product.

**Comment by Cosmos491** [comment]
I can work towards developing the mathematics

**Comment by abruns123** [comment]
I can work on Experimental Tests for Bell's inequality

**Comment by HeshamElsaman** [comment]
I suggest adding a section about the loopholes in the Bell test.
You can look up the book "Introduction to Quantum Computing" by Ray LaPierre (page 89).

**Comment by ojha-aditya** [comment]
I think we can close this issue now as most of the documentation is done. Closing for now, if needed we could reopen I guess.
