### ISSUE TITLE
Need help on pull request.

### ISSUE THREAD

**Issue by kylemasc917** [ubsuny/CP1-24-HW1#43]
Does anyone happen to know how to remove a specific file from a pull request?

**Comment by SchrodingersStruggle** [comment]
This is an idea, and could be wrong, but on my pull request if I look at an individual commit and then hit the three dots on top of the file, it gives me a prompt to delete the file. Not sure if that just deletes the file from the pull request, or all together, so a second opinion / test on your personal repo to see if it works may be a good idea.

**Comment by laserlab** [comment]
Perfect answer @SchrodingersStruggle

**Comment by kylemasc917** [comment]
Thank you that seemed to work the pull request has bee updated.
