### ISSUE TITLE
Created citation.

### ISSUE THREAD

**Issue by kylemasc917** [ubsuny/CP1-24-HW1#44]
I created a citation for my background markdown file in my forked repository if anyone needs to use the text I wrote up. It can be found here: https://github.com/kylemasc917/CP1-24-HW1 and clicking "Cite this Repository" on the right-hand side.

**Comment by laserlab** [comment]
That is not necessary since your text will be automatically referenced through the pull request. Can you please address the comments in your PR #30 so it can be merged?

**Comment by laserlab** [comment]
please add milestone and label

**Comment by kylemasc917** [comment]
> That is not necessary since your text will be automatically referenced through the pull request. Can you please address the comments in your PR #30 so it can be merged?

Ok I will close this, and the unneeded file has been removed from the pull request. It should be ready for merge unless there are further problems.
