### ISSUE TITLE
Help, I have no idea what I'm doing

### ISSUE THREAD

**Issue by p-pxmpo** [ubsuny/CP1-24-HW1#46]
So from my understanding were supposed to write the bell inequality code as well as the markdown file in our OWN computers/repositores, then push those files into this (ubsuny) repository? That being said what is the quantumcode.py in the main repository, is that the code for the bell's inequality? thanks

**Comment by laserlab** [comment]
Your understanding is not correct. As stated in the homework assignment you should participate in the discussions to discuss possible homework tasks.

**Comment by dnxjay** [comment]
Half of the points from this assignment is from the feedback that we give and participation in discussions.

**Comment by jkblc** [comment]
Looks like you made a commit, so keep working on something and open a pull request. It doesn't have to be major, maybe add to the documentation.
