### ISSUE TITLE
Some ideas on where to start

### ISSUE THREAD

**Issue by avgagliardo** [ubsuny/CP1-24-HW1#5]
We talked a little bit about the assignment today, but "Implement Bell's inequality" is still a very high level goal. We'll probably talk more about it on Wednesday, but in the meantime I was thinking that maybe we could brainstorm around some deliverable-oriented questions. Specifically there's two questions I always start with on any new project:

### **What should it do?** 
Conceptually, we know what we want to develop (a system that implements Bell's inequality) but explicitly asking what it should do is a little bit more tangible and might suggest potential paths for initial development. For example, one possible consideration might be that if the system is stateful (I assume that it is) are there certain input/output states that we especially care about? Are there any essential algorithms or data structures that need to be generalized-- or in the opposite case, that need to be hand-tailored to meet our needs?

### **How do we know that it's working?** 
There are usually a lot of ways to approach answering this question, but sometimes thinking about it before you start primary development can help you identify and catch problems before they become issues that require changes to the approach/architecture/codebase, etc. Similarly, when it comes to writing unit tests it's usually pretty straightforward to catch malfunctioning code but it's much more difficult to catch code that executes (or is formed) properly, but that is conceptually incorrect. Sometimes these are called "modeling bugs" or "conceptual bugs" and they are notorious for being difficult to identify.

### **What do you think?**
Open to all suggestions. Feel free to drop more high level questions in here too. If we need more than one thread for it, we might want to make a `Brainstorm` label.

Edit: Seems like I cant assign labels, projects, milestones, etc. It's probably a repository level admin setting so I'll just update those fields whenever the permissions are in place. Thanks!

**Comment by laserlab** [comment]
@avgagliardo For now I just comment on the access problems (labels, ...). Everybody who works on the repository (comments, opens an issue) gets an invitation to join UBsuny on github. Once you accept you should be able to have more access.

**Comment by laserlab** [comment]
@avgagliardo are you able to make a brainstorm label after you are a member of the @CP1-24 team? You can also open a new issue for this

**Comment by laserlab** [comment]
@avgagliardo I have a suggestion. Your questions are very valid and a good starting point for specific items of the project. Let’s break it down into two points
1. What should it do: I would suggest to find some code examples that already do something similar (e.g.-> https://learning.quantum.ibm.com/tutorial/chsh-inequality). That could be your task for this homework. Find a code example and add it to this repository (if license allows).
2. How do we know it is working. This would be centered around unit testing. This could be your homework task. Come up (not necessarily in code but also pseudocode) what outcomes you would expect for the bell inequality for specific inputs.

**Comment by laserlab** [comment]
@Priyanka-43 Referencing issue #10 here. Please let me know if you can make labels now.

**Comment by Priyanka-43** [comment]
Yes, I can make label now. Thankyou.

**Comment by avgagliardo** [comment]
> @avgagliardo are you able to make a brainstorm label after you are a member of the @CP1-24 team? You can also open a new issue for this

Still not having any luck. I split this out into issue #12

**Comment by jkblc** [comment]
I would add that the Qiskit YouTube channel has a video explaining Bell's inequality [here](https://www.youtube.com/watch?v=9OM0jSTeeBg). Helping write the actual code in Qiskit sounds fun to me.

**Comment by avgagliardo** [comment]
> @avgagliardo I have a suggestion. Your questions are very valid and a good starting point for specific items of the project. Let’s break it down into two points
> 
> 1. What should it do: I would suggest to find some code examples that already do something similar (e.g.-> https://learning.quantum.ibm.com/tutorial/chsh-inequality). That could be your task for this homework. Find a code example and add it to this repository (if license allows).
> 2. How do we know it is working. This would be centered around unit testing. This could be your homework task. Come up (not necessarily in code but also pseudocode) what outcomes you would expect for the bell inequality for specific inputs.

Unit testing sounds like it might be fun. I'll start looking into it.

**Comment by laserlab** [comment]
> I would add that the Qiskit YouTube channel has a video explaining Bell's inequality [here](https://www.youtube.com/watch?v=9OM0jSTeeBg). Helping write the actual code in Qiskit sounds fun to me.

This could be your homework task (though maybe with others to participate). Why don’t you start and write a couple of lines and open a pull request.

**Comment by laserlab** [comment]
> > @avgagliardo I have a suggestion. Your questions are very valid and a good starting point for specific items of the project. Let’s break it down into two points
> > 
> > 1. What should it do: I would suggest to find some code examples that already do something similar (e.g.-> https://learning.quantum.ibm.com/tutorial/chsh-inequality). That could be your task for this homework. Find a code example and add it to this repository (if license allows).
> > 2. How do we know it is working. This would be centered around unit testing. This could be your homework task. Come up (not necessarily in code but also pseudocode) what outcomes you would expect for the bell inequality for specific inputs.
> 
> Unit testing sounds like it might be fun. I'll start looking into it.

Why don’t you start in writing down some conceptual unit tests and open a pull request.

**Comment by avgagliardo** [comment]
> > > @avgagliardo I have a suggestion. Your questions are very valid and a good starting point for specific items of the project. Let’s break it down into two points
> > > 
> > > 1. What should it do: I would suggest to find some code examples that already do something similar (e.g.-> https://learning.quantum.ibm.com/tutorial/chsh-inequality). That could be your task for this homework. Find a code example and add it to this repository (if license allows).
> > > 2. How do we know it is working. This would be centered around unit testing. This could be your homework task. Come up (not necessarily in code but also pseudocode) what outcomes you would expect for the bell inequality for specific inputs.
> > 
> > 
> > Unit testing sounds like it might be fun. I'll start looking into it.
> 
> Why don’t you start in writing down some conceptual unit tests and open a pull request.

sounds good, I can start working on that today.

**Comment by laserlab** [comment]
@avgagliardo Do you want to keep this issue open? Btw. issues that are not looked into in a while usually get a “stale” label.
