### ISSUE TITLE
Commit from codespace

### ISSUE THREAD

**Issue by ojha-aditya** [ubsuny/CP1-24-HW1#50]
Does anyone using codespaces remember how to commit a change directly from the codespace? For example if we create a Jupyter notebook in the codespace environment and try to commit the same to a branch on our forked repository.

**Comment by HeshamElsaman** [comment]
I guess you can use that forking symbol on the side in your codespace to add the changes and then commit them.

**Comment by ojha-aditya** [comment]
Got it! Thanks a lot.
