### ISSUE TITLE
Codespace Explorer Issue

### ISSUE THREAD

**Issue by HeshamElsaman** [ubsuny/CP1-24-HW1#51]
Although my repo is up to date with the main repo, my codespace is not showing any content other than the .divcontainer and README.md. Can somebody help, please?

**Comment by laserlab** [comment]
You have to sync your fork: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

**Comment by HeshamElsaman** [comment]
I did. It's already synced. The issue persists.

**Comment by laserlab** [comment]
rebuild the codespace

**Comment by laserlab** [comment]
or wrong branch the codespace is running in

**Comment by HeshamElsaman** [comment]
I rebuilt it and I believe it worked out. Thanks!
