### ISSUE TITLE
Any open topics to claim

### ISSUE THREAD

**Issue by HeshamElsaman** [ubsuny/CP1-24-HW1#52]
I can't think of any task I can handle.
Is it possible to tackle steps 3 and 4 of the code part for example?

**Comment by laserlab** [comment]
Did you check the help wanted issues?

**Comment by HeshamElsaman** [comment]
Yes, I've already checked all of the issues.
I double-checked them again now, and I still can't recognize an open task per se.
What I can recognize is the issue with the missing .gitignore and the restructuring of the READ.ME file.
To my understanding and observation, the issue with the missing .gitignore is already solved yet the issue is still opened just to add to it?
And for the READ.ME file, I can't really tell whether it's still needed.
And since I was aiming for the coding part, it was the clearest to me.

**Comment by laserlab** [comment]
As I said in #24 
 https://github.com/ubsuny/CP1-24-HW1/issues/24#issuecomment-2365208610

the .gitignore is only one line right now and has to be appended. So that is an open task.

**Comment by HeshamElsaman** [comment]
Alright, I will work on it.
