### ISSUE TITLE
Task up for the taking for whoever wants it

### ISSUE THREAD

**Issue by SchrodingersStruggle** [ubsuny/CP1-24-HW1#58]
Hello, 
I was originally working on a task where I was to edit the in-line descriptions of what is going on in the current quantum.py file in order to more clearly explain what each step is doing in the context of Bell's inequality, particularly for the section leading up to assigning observables. 

However, I have now submitted my second pull request on a different topic I found myself in, so I will not benefit from doing this task grade wise anymore. I want to leave this for someone else to do who can benefit from credit, so feel free to claim it. Any questions feel free to ask!

**Comment by HeshamElsaman** [comment]
Hi,

I guess I can take that

**Comment by SchrodingersStruggle** [comment]
Okay sounds good. Any questions feel free to let me know

**Comment by HeshamElsaman** [comment]
Great, thanks!
