### ISSUE TITLE
Another thing to start considering.

### ISSUE THREAD

**Issue by kylemasc917** [ubsuny/CP1-24-HW1#6]
Given the number of individuals in class and the assignment, we should start thinking about how we want to divide the work evenly so that everyone has a chance to contribute and complete the assignment. 

I'm making this issue for anyone that wants to start discussing that.

**Comment by laserlab** [comment]
There is plenty to do, check the READ.ME for ideas. I also will give some more examples in class on Wednesday.

**Comment by laserlab** [comment]
@kylemasc917 please add label(s) and milestone to your issue.

**Comment by Priyanka-43** [comment]
I have the same query, regarding, how we are going to proceed.

**Comment by laserlab** [comment]
@Priyanka-43 Why don’t you suggest which part you would like to do? You can do that in a new issue.

**Comment by abruns123** [comment]
I would be okay with helping to write the markdown file explaining the physics.

**Comment by Priyanka-43** [comment]
Yeah sure, we can do that.

**Comment by laserlab** [comment]
@abruns123 @Priyanka-43 That is great. Make sure you keep the workflow and work together through issues and pull requests

**Comment by kylemasc917** [comment]
I pull requested a markdown file on EPR paradox I will close this issue for now as there are other issues that handle this.

**Comment by kylemasc917** [comment]
I pull requested a markdown file on EPR paradox I will close this issue for now as there are other issues that handle this.
