### ISSUE TITLE
Reorganization of the Existing Files

### ISSUE THREAD

**Issue by iamtomato761** [ubsuny/CP1-24-HW1#61]
It might be better to reorganize the files into a coding section and for documentation.

**Comment by laserlab** [comment]
This is a great idea, why don’t you put it in a PR and we decide then. THis could be your homework task to keep the repo structure useful.

**Comment by laserlab** [comment]
please add a label and milestone

**Comment by iamtomato761** [comment]
I've labeled this as part of documentation and architecture since the issue was to reorganize the documentation a bit
