### ISSUE TITLE
How do I know my role for this homework?

### ISSUE THREAD

**Issue by dnxjay** [ubsuny/CP1-24-HW1#65]
As seen in a previous issue, it states that not everyone will code and it would be explained more in last Wednesdays lecture but i was unable to attend. I thought i had an idea on the homework but now im lost, what will i be doing between code or documentation?

**Comment by Priyanka-43** [comment]
I have also same query.

**Comment by iamtomato761** [comment]
The amount of coding you do depends on the task(s) you choose. I personally have chosen to do some reorganization as I am just trying to get used to GitHub and this homework style this time around. If you would like to help, we are discussing some more changes in issue #67

**Comment by dnxjay** [comment]
Okay thats fair. My question to that is am i allowed to do the same? Im also new to github so trying to familiar myself with things but seems like missing one lecture feels like alot because of the quick pace.

**Comment by avgagliardo** [comment]
> Okay thats fair. My question to that is am i allowed to do the same? Im also new to github so trying to familiar myself with things but seems like missing one lecture feels like alot because of the quick pace.

We could always use more help commenting the code as well!

**Comment by iamtomato761** [comment]
> Okay thats fair. My question to that is am i allowed to do the same? Im also new to github so trying to familiar myself with things but seems like missing one lecture feels like alot because of the quick pace.

We are allowed to work on similar tasks! If I remember correctly, he said he even encourages it to some degree. I have no problem with you submitting a pull request that challenges mine, as I have little idea what I am doing, so everything is merely a suggestion.

**Comment by p-pxmpo** [comment]
So are we just supposed to just pick and choose what we do in this homework?

**Comment by laserlab** [comment]
> So are we just supposed to just pick and choose what we do in this homework?

To a certain degree yes. This mostly applies to the early stages in the homework discussion. Now it is a little bit on the late side, and there are open tasks under the help wanted labels

**Comment by dnxjay** [comment]
> > So are we just supposed to just pick and choose what we do in this homework?
> 
> To a certain degree yes. This mostly applies to the early stages in the homework discussion. Now it is a little bit on the late side, and there are open tasks under the help wanted labels

I feel like this initial part of the task wasn't emphasized enough. I got flustered at the start trying to learn the new interface and missed out on some of those discussions and also not fully knowing what the assignment was

**Comment by avgagliardo** [comment]
> > > So are we just supposed to just pick and choose what we do in this homework?
> > 
> > 
> > To a certain degree yes. This mostly applies to the early stages in the homework discussion. Now it is a little bit on the late side, and there are open tasks under the help wanted labels
> 
> I feel like this initial part of the task wasn't emphasized enough. I got flustered at the start trying to learn the new interface and missed out on some of those discussions and also not fully knowing what the assignment was

I have a PR coming soon that has a bunch of TODOs. Feel free to take any of them out if you like.

Hoping to push in the next couple hours.

**Comment by dnxjay** [comment]
> > > > So are we just supposed to just pick and choose what we do in this homework?
> > > 
> > > 
> > > To a certain degree yes. This mostly applies to the early stages in the homework discussion. Now it is a little bit on the late side, and there are open tasks under the help wanted labels
> > 
> > 
> > I feel like this initial part of the task wasn't emphasized enough. I got flustered at the start trying to learn the new interface and missed out on some of those discussions and also not fully knowing what the assignment was
> 
> I have a PR coming soon that has a bunch of TODOs. Feel free to take any of them out if you like.
> 
> Hoping to push in the next couple hours.

Okay, ill keep a look out for it.

**Comment by dnxjay** [comment]
> I have also same query.

Feeling any better about this assignment? I'm Starting to pick up an idea of whats going on so feel free to respond with questions.

**Comment by avgagliardo** [comment]
> > > > > So are we just supposed to just pick and choose what we do in this homework?
> > > > 
> > > > 
> > > > To a certain degree yes. This mostly applies to the early stages in the homework discussion. Now it is a little bit on the late side, and there are open tasks under the help wanted labels
> > > 
> > > 
> > > I feel like this initial part of the task wasn't emphasized enough. I got flustered at the start trying to learn the new interface and missed out on some of those discussions and also not fully knowing what the assignment was
> > 
> > 
> > I have a PR coming soon that has a bunch of TODOs. Feel free to take any of them out if you like.
> > Hoping to push in the next couple hours.
> 
> Okay, ill keep a look out for it.

PR is live, but not merged if you want to check it out. There are more TODOs coming, but before I commit them I wanted to make sure that we do indeed intend to replace the quantumcode.py file that was deleted earlier today.
