### ISSUE TITLE
Should we change the README file?

### ISSUE THREAD

**Issue by SchrodingersStruggle** [ubsuny/CP1-24-HW1#67]
Just wondering (and also an idea for some tasks for others), should we keep the README as a file which describes the general grading scheme of the project, or should we change it to actually give a quick description of the files in the repository amongst other things to make the README more useful to the project in general. 

We could make the current README into a separate file (named grading rubric or something of the sort), or we could leave it as is and just keep making separate markdown files to describe the repository.

**Comment by iamtomato761** [comment]
I like the idea of titling the current file something like "grading rubric" or even just "homework details." I also like the idea of having a description of the files somewhere. Do you think we should add a new file with a description of all the files or are you saying this could all be in README?

**Comment by dnxjay** [comment]
I think adding a new file would be nice. Also I feel like some of this tasks could've had a better structure

**Comment by laserlab** [comment]
There is actually issue #25 on it. and this should definitely be done

**Comment by SchrodingersStruggle** [comment]
Closing this issue as it was referenced earlier, and people seem to have claimed the task.
