### ISSUE TITLE
What should the path look like to link files?

### ISSUE THREAD

**Issue by iamtomato761** [ubsuny/CP1-24-HW1#70]
I am linking the HowToRun.md and Physics_Documentation.md files to what is currently the README.md. What I currently have includes my username and branch in the path. Is there a better way to link files or does that work with a PR and merge?

```python
[Link Text](https://github.com/username/repo/blob/branch/path/to/file.md)

**Comment by laserlab** [comment]
There are basically two ways. A relative link to the current version of a file (which is in general discouraged tsince it can change) or the permalink (specific version of a file) as in your example.

**Comment by iamtomato761** [comment]
Ok, thank you! Makes sense.
