### ISSUE TITLE
File organization

### ISSUE THREAD

**Issue by p-pxmpo** [ubsuny/CP1-24-HW1#75]
Would it be possible to create a new folder containing the markdown files that explain the physics? I see 3 seperate files that does that.

**Comment by ojha-aditya** [comment]
Or how about we merge the markdown files explaining Physics into a single one by tomorrow maybe, once more people have submitted their PRs?

**Comment by iamtomato761** [comment]
Thank you for merging the files! Looks good. I will help clean up the rest and organize some more.
