### ISSUE TITLE
quantumcode.py missing

### ISSUE THREAD

**Issue by avgagliardo** [ubsuny/CP1-24-HW1#77]
I was working on integrating quantumcode.py to some of the other files, but I noticed its gone missing.  It looks like it was deleted with PR #66.

Was quantumcode.py intentionally deleted because it's functionality was rolled into another file? I no longer see it in the main repo, and I don't see any files that seem to replace it. Maybe it happened somehow by accident during today's demo?

I still have a local version I was working that I can restore (with my edits) if we want to roll it back.

**Comment by HeshamElsaman** [comment]
Yes, it was deleted with that pull request.

**Comment by avgagliardo** [comment]
> Yes, it was deleted with that pull request.

But I'm assuming it was not deliberate, correct? I restored it in my last PR since that seems like the natural place for our code to live. 

If it was deleted intentionally, please let me know.

**Comment by jkblc** [comment]
It was deleted during class today and was not restored before that pull request was merged. Can we revoke that merge @laserlab

**Comment by jkblc** [comment]
There is a new pull request that adds the file back. Thanks @avgagliardo

**Comment by avgagliardo** [comment]
If it was just that file and the python directory that were removed it might be easier to merge #80 rather than rollback.

**Comment by HeshamElsaman** [comment]
@avgagliardo yeah, I guess it was not deliberately deleted as well, unless @laserlab says otherwise

**Comment by HeshamElsaman** [comment]
I was just about to start working on it when I freaked out because of the issue you raised about the file being missing

**Comment by laserlab** [comment]
Was removed by accident by the PR from lecture. Good example for how useful a version control system is. Not just that all of you have a copy, it is also always possible to go to an old version to restore it. Fixed by PR #80
