### ISSUE TITLE
Challenge: Will it Run?

### ISSUE THREAD

**Issue by avgagliardo** [ubsuny/CP1-24-HW1#78]
### The problem: Will it Run?
So far (with my own attempts included) I haven't seen anyone actually execute the program remotely. I've gotten local versions to work, but that is trivial since its just a simulation, but more importantly part of the project involves using the IBM API to execute our job remotely-- and that is non-trivial.

I will help with catching exceptions and debugging the communication layers, but we definitely need to get this thing into a state where it is at a minimal viable product (maybe project instead of product, in this case) if we want to be able to iteratively develop while getting feedback on the project's functionality.

### The Solution: A Reward
Be the first one to execute the program (and document it!) in order to claim the prize! For this project (and maybe future ones...) the first person to post their proof in this thread will be awarded a customized golden developer prize-crown as their trophy.

**Comment by avgagliardo** [comment]
Also as a quick note, be sure to **not post** (or blur out) anything sensitive like API keys, etc

**Comment by p-pxmpo** [comment]
I tried executing the code but I dont think I did it correctly because it took 5 minutes to run and the system just timed out

**Comment by laserlab** [comment]
@avgagliardo Did you see the IBM API documentation in [ IBM Quantum API Information.md](https://github.com/ubsuny/CP1-24-HW1/blob/0d8bbc7dee2bda99fb44a001333a504f3470857b/IBM%20Quantum%20API%20Information.md)

**Comment by ojha-aditya** [comment]
In line with this issue actually, I guess we need to consolidate what counts as the task completion, is it to have a working code or something more general? 

Splitting in a new issue.

**Comment by avgagliardo** [comment]
Following up with an example of code that will execute remotely, check out PR #97  

It shouldn't be merged since it uses a different architecture, but it implements the connection to IBM's backend provider if anyone wanted a reference.
