### ISSUE TITLE
Proposal for "Consolidation" and "Award Available" labels

### ISSUE THREAD

**Issue by avgagliardo** [ubsuny/CP1-24-HW1#79]
I'd like to propose two new tags:

Consolidation - For issues that have multiple threads, we could use this label to merge them all into a single turbo-thread if/when it becomes necessary.

Award Available - For subgoals that have minor prizes/awards attached to their completion. For example, see issue #78 -- I've offered a minor award to the first person who can document that they've managed to execute the program on IBM's system.

**Comment by laserlab** [comment]
Great ideas. You got them
