### ISSUE TITLE
Clarification about HW code submission

### ISSUE THREAD

**Issue by ojha-aditya** [ubsuny/CP1-24-HW1#8]
@laserlab Could we clarify whether the actual Bell's inequality code is meant to be different for everyone or whether like the rest of the assignment, the entire class works on the code together? 

Maybe we could discuss some more about the assignment in the Wednesday class?

**Comment by Priyanka-43** [comment]
I think we have to work on the same code. But rest we can discussed in class.

**Comment by laserlab** [comment]
Everyone will work on a different task of the project as laid out in the homework description. Not everyone will code for example. Some might write a documentation part, some might lint code written by someone else. While we go through lecture on Wednesday I will have more examples.

**Comment by Priyanka-43** [comment]
I will create markdown documentation file and will be responsible for documenting the problem.

**Comment by ojha-aditya** [comment]
Alright! Got it.
