### ISSUE TITLE
Equation in Markdown file

### ISSUE THREAD

**Issue by Priyanka-43** [ubsuny/CP1-24-HW1#86]
I have been searching on how to write equation on markdown file nicely. I found that same notations used in Latex and Katex can be used. I am sharing these information, it might be useful for you.

**Comment by iglesias-cardinale** [comment]
I've found it to be particularly useful to use the Latex style when documenting my code. It makes it super efficient when you want to put what you've done into a paper format when you have results you want to publish. You can basically just copy and paste your md file into your Latex compiler and a lot of the work is already done for you.

**Comment by Priyanka-43** [comment]
Ok. Thankyou so much.
