### ISSUE TITLE
Add Image

### ISSUE THREAD

**Issue by dhamalakamal** [ubsuny/CP1-24-HW1#88]
How to add images in the documentation file?

**Comment by ojha-aditya** [comment]
The ! mark is the image command, you can look here maybe https://www.markdownguide.org/basic-syntax/#images-1

It needs to have a path description for the image

**Comment by dhamalakamal** [comment]
![image](https://github.com/user-attachments/assets/afcb76f7-68ca-4289-988f-42c86ca2d46e)

**Comment by dhamalakamal** [comment]
Thanks.
