### ISSUE TITLE
Task completion?

### ISSUE THREAD

**Issue by ojha-aditya** [ubsuny/CP1-24-HW1#89]
Mostly some more members are confused about this too, so splitting #78 into a different issue. 

@laserlab based on the grading rubric, what exactly counts as task completion, since it is not in the shared points, is it different for everyone because as was discussed in #8 not everyone needs to do each task, so is it like having one final markdown file on physics and one final working code for the entire team?

**Comment by p-pxmpo** [comment]
I think @laserlab said that we can just pick and choose our tasks to a certain degree

**Comment by p-pxmpo** [comment]
#65

**Comment by laserlab** [comment]
The task completion is more traditional grading. When you have done your task it has to go into a PR. If I comment on the PR with suggestions what to change then it’s not full points yet.

**Comment by laserlab** [comment]
The choosing your homework is mostly related to the beginning when we discuss what to do. See e.g. #5 how that goes.

**Comment by laserlab** [comment]
add label and. milestone

**Comment by ojha-aditya** [comment]
Will close this as well now that we are almost done with the HW completion
