### ISSUE TITLE
Task Distribution

### ISSUE THREAD

**Issue by Priyanka-43** [ubsuny/CP1-24-HW1#9]
I will create markdown documentation file and will be responsible for documenting the problem.

**Comment by laserlab** [comment]
Awesome. If you are already familiar with the github workflow why don’t you fork the repository, generate a first draft of the file and open a pull request. Once that is done close this issue.
Also add a milestone and a label to this issue

**Comment by avgagliardo** [comment]
> I will create markdown documentation file and will be responsible for documenting the problem.

I think I will start thinking in the direction of unit testing, unless someone else is interested.

**Comment by laserlab** [comment]
> > I will create markdown documentation file and will be responsible for documenting the problem.
> 
> I think I will start thinking in the direction of unit testing, unless someone else is interested.

See my comment in #5

**Comment by kylemasc917** [comment]
I can start working on a Markdown file for the background physics of the problem as well. That way we can compare what we write and combine them for the final Markdown file.

**Comment by kylemasc917** [comment]
I can focus more on the EPR paradox that Bell was answering.

**Comment by laserlab** [comment]
@kylemasc917 That sounds like a great idea. Try to start writing about EPR and open a pull request and then we can see how to combine it.
