### ISSUE TITLE
When is it appropriate to close an issue?

### ISSUE THREAD

**Issue by iglesias-cardinale** [ubsuny/CP1-24-HW1#92]
I would imagine it's generally good practice for one to only close issues that they themselves opened. But I'm not sure if that's proper or if you should close an issue once that the issue has been resolved.

**Comment by avgagliardo** [comment]
If it seems like the issue is dead, maybe quote the original post and let them know it might be worth closing the issue. If there's no response, then it is probably safe to close it.

**Comment by laserlab** [comment]
Ideally the person who opened closes the issue.

**Comment by laserlab** [comment]
Keep it open if it is not resolved

**Comment by dnxjay** [comment]
usually closed by the person who opens it and feels like its resloved

**Comment by iglesias-cardinale** [comment]
Thanks. This makes sense!
